// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// avgDist
double avgDist(NumericMatrix pointMatrix);
RcppExport SEXP SPAG_avgDist(SEXP pointMatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type pointMatrix(pointMatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(avgDist(pointMatrix));
    return rcpp_result_gen;
END_RCPP
}
